### ISSUE TITLE
Snap-Chromium eating disk space

### ISSUE THREAD

**Issue by bouncingcandle** [sensepost/gowitness#200]
**Describe the bug**
As Snap Chromium is used for GoWitness, it will fill up the '/tmp' directory until is has either finished or disk usage is at 100%.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a list of subdomains 9190 lines long
2. Have 9GB of disk space free
3. Run GoWitness
4. Wait for Subdomain on line ~4713 to be reached
5. See process has hung and disk usage is 100%

**Expected behaviour**
Disk not the be filled up and clutter to be automatically removed.

**Version Information:**
 - OS: Ubuntu 20.04.6
 - gowitness: 2.5.0

**Additional context**
I have a list of 9190 subdomains. My tmp folder was empty, as I had just recently restarted my server. Upon checking back a day later, I noticed it had hung and when checking my disk usage, I was a 100% with 6.9GB '/tmp' folder, 6.9GB of which being '/tmp/snap-private-tmp/snap.chromium'. I checked what line the last subdomain was at, and it only made it to line 4713 before reaching 100% disk usage.

**Comment by bouncingcandle** [comment]
I should also add that in '/tmp/snap-private-tmp/snap.chromium/tmp' I have 2756 folders of 'chromedp-runner' profiles.

**Comment by bouncingcandle** [comment]
I just want to add my workaround just in case anyone faces the same issue, it may not be desirable but it works:
`DISCLAIMER: Only do this is you're ONLY using Snap Chromium for GoWitness. This will delete any profiles or runners you have setup for your headless Chromium or other tools/scripts.`

Add `user ALL=(ALL:ALL) NOPASSWD: /bin/rm -rf /tmp/snap-private-tmp/snap.chromium` to the bottom of `/etc/sudoers`

Before running GoWitness:
```BASH
mkdir "https-split" && cd "$_"
split -l 500 "../https.txt"
cd ..
```

Then run GoWitness with:
```BASH
for file in https-split/*; do
  gowitness file -X 2560 -Y 1440 -F -f "$file" -t 1
  sudo rm -rf /tmp/snap-private-tmp/snap.chromium*
done
```

**Comment by leonjza** [comment]
For v3, I've added logic to isolate user directories between runs which will cleanup when done. Hopefully that helps here.

**Comment by oped6700** [comment]
The tmp directory is fixed, but it will generate.pma files in this directory:
/root/snap/chromium/common/chromium/DeferredBrowserMetrics

You can't take a screenshot if you delete both directories

**Comment by oped6700** [comment]
> The tmp directory is fixed, but it will generate.pma files in this directory: /root/snap/chromium/common/chromium/DeferredBrowserMetrics
> 
> You can't take a screenshot if you delete both directories

I see why, don't download chrome with snap -google can just use your method

**Comment by oped6700** [comment]
> The tmp directory is fixed, but it will generate.pma files in this directory: /root/snap/chromium/common/chromium/DeferredBrowserMetrics
> 
> You can't take a screenshot if you delete both directories

I see why, don't use snap to download chrome, your method works

**Comment by lappsec** [comment]
@leonjza Just an FYI, I'm still having this issue with v3.0.4 on Ubuntu 20.04 LTS and Chromium 131.0.6778.85 (snap). Those folders /tmp/snap-private-tmp/snap.chromium/tmp take up a ton of space and are not cleared out after running. So all 15GB of free disk space gets eaten up with a gowitness run on 2500 hosts.
